### ISSUE TITLE
armadillo-5.200.1+openblas with visual studio 2010

### ISSUE THREAD

**Issue by ghost** [chang48/QUEST#62]
Hello,

I have been trying to make armadillo-5.200.1 and openblas work with visual studio 2010 since a week now and I still have several unresolved external symbols errors with functions from the blas and lapack libraries.
First, I tried to install openblas from pre-built binaries for windows and set up a new project and test it with the sample code below:

``` C++
#include <cblas.h>
#include <iostream>
#include <vector>

using namespace std;

int main()
{
    blasint n = 10;
    blasint in_x =1;
    blasint in_y =1;

    std::vector<double> x(n);
    std::vector<double> y(n);

    double alpha = 10;

    std::fill(x.begin(),x.end(),1.0);
    std::fill(y.begin(),y.end(),2.0);

    cblas_daxpy( n, alpha, &x[0], in_x, &y[0], in_y);

    //Print y
    for(int j=0;j<n;j++)
        std::cout << y[j] << "\t";

    std::cout << std::endl;
}
```

I got an unresolved external symbol « cblas_daxpy » error. I tried to build the same project with code::blocks and got the same error. 

Finally, I downloaded and set up msys to be able to compile the source I downloaded on github (https://github.com/xianyi/Openblas) and tried to make it work both on code::blocks and visual studio, but I still got the same errors.

Then I tried on my own laptop, because it has Linux ubuntu 14.04 LTS. So, I cloned the github and compiled the sources and tried to set it up in another code::blocks project and I test it using the same sample code and got undefined reference errors concerning functions such as pthread_create and pthread_join.

To use openblas with visual studio, I followed the instructions about third-party library: 
- add the location of the header files to "C/C++->Additional Include Directories"
- add the .lib files to the "Linker->Input->Additional Dependencies" 
- add the location of the .lib files to "Linker->General->Additional Library Directories" 

For code::bocks, I followed the instructions of this webpage http://www.learncpp.com/cpp-tutorial/a3-using-libraries-with-codeblocks/

I need to make this work at least with windows 7 and better with visual studio 2010, because we use it at work.

**Comment by chang48** [comment]
I'm sorry, but this is not a QUEST related issue.
